#!/bin/bash
# Appwrite Deployment Quick Reference

set -e

echo "╔════════════════════════════════════════════════════════════════════════════════╗"
echo "║                     Appwrite Deployment Pipeline Setup                         ║"
echo "╚════════════════════════════════════════════════════════════════════════════════╝"

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "\n${BLUE}Step 1: Generate Secrets${NC}"
echo "Run these commands and save the output:"
echo ""
echo "  OPENSSL_KEY_V1 (copy to .env.prod):"
openssl rand -base64 32
echo ""
echo "  EXECUTOR_SECRET (copy to .env.prod):"
openssl rand -base64 32
echo ""

echo -e "\n${BLUE}Step 2: Configure Environment${NC}"
echo "1. Copy environment template:"
echo "   cp .env.prod.example .env.prod"
echo ""
echo "2. Edit with your values:"
echo "   nano .env.prod"
echo ""
echo "3. Verify your configuration:"
echo "   - APP_DOMAIN, CONSOLE_DOMAIN"
echo "   - Database credentials"
echo "   - SMTP settings"
echo "   - Storage settings"
echo ""

echo -e "\n${BLUE}Step 3: Set GitHub Secrets${NC}"
echo "Add these to your GitHub repository (Settings → Secrets):"
echo ""
echo "  DOCKER_HUB_USERNAME"
echo "  DOCKER_HUB_PASSWORD"
echo "  DEPLOY_SSH_KEY"
echo "  DEPLOY_HOST"
echo "  DEPLOY_USER"
echo "  KUBE_CONFIG (for Kubernetes)"
echo ""

echo -e "\n${BLUE}Step 4: Choose Deployment Strategy${NC}"
echo ""
echo "  ${GREEN}Option A: Docker Compose${NC} (Single server)"
echo "    Best for: Small/medium deployments"
echo "    Setup: Copy .env.prod to server and run:"
echo "    $ docker compose -f docker-compose.prod.yml up -d"
echo ""
echo "  ${GREEN}Option B: Kubernetes${NC} (Multi-node, HA)"
echo "    Best for: Large deployments, auto-scaling"
echo "    Setup: kubectl apply -f k8s/appwrite-deployment.yaml"
echo ""
echo "  ${GREEN}Option C: Docker Swarm${NC} (Docker-native)"
echo "    Best for: Medium deployments"
echo "    Setup: docker stack deploy -c docker-compose.prod.yml appwrite"
echo ""

echo -e "\n${BLUE}Step 5: Set Up Monitoring${NC}"
echo "Recommended monitoring stack:"
echo "  - Prometheus (metrics)"
echo "  - Grafana (dashboards)"
echo "  - ELK Stack (logs)"
echo "  - Alertmanager (alerts)"
echo ""

echo -e "\n${BLUE}Step 6: Verify Deployment${NC}"
echo ""
echo "Docker Compose:"
echo "  $ docker compose -f docker-compose.prod.yml ps"
echo "  $ curl http://localhost/health"
echo ""
echo "Kubernetes:"
echo "  $ kubectl rollout status deployment/appwrite -n appwrite-production"
echo "  $ kubectl get pods -n appwrite-production"
echo ""

echo -e "\n${BLUE}Available Workflows${NC}"
echo ""
echo "  1. ${GREEN}build-and-test.yml${NC}"
echo "     Triggers: Push to main/develop, Pull Requests"
echo "     Actions: Build, test, lint, security scan"
echo ""
echo "  2. ${GREEN}push-to-registry.yml${NC}"
echo "     Triggers: Push to main, Git tags"
echo "     Actions: Build and push to Docker Hub"
echo ""
echo "  3. ${GREEN}deploy-k8s.yml${NC}"
echo "     Triggers: Push to main, Git tags, Manual"
echo "     Actions: Deploy to Kubernetes"
echo ""
echo "  4. ${GREEN}deploy-compose.yml${NC}"
echo "     Triggers: Push to main, Git tags"
echo "     Actions: SSH deploy with Docker Compose"
echo ""

echo -e "\n${BLUE}Documentation${NC}"
echo "  - DEPLOYMENT.md          Full deployment guide"
echo "  - SECURITY.prod.md       Production security policies"
echo "  - .env.prod.example      Configuration template"
echo "  - k8s/appwrite-deployment.yaml  Kubernetes manifests"
echo "  - docker-compose.prod.yml       Production compose file"
echo ""

echo -e "\n${GREEN}✓ Setup Complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Generate secrets (Step 1 above)"
echo "  2. Configure .env.prod"
echo "  3. Add GitHub secrets"
echo "  4. Choose deployment strategy"
echo "  5. Push to GitHub to trigger pipeline"
echo ""
echo "For detailed instructions, see DEPLOYMENT.md"
echo ""
